name: deploy
on:
  push:
    tags:
    - '*'
jobs:
  lint:
    runs-on: ['ubuntu-22.04']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.16'
      - run: npm install
      - run: touch jnitrace/build/__init__.py
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}