name: lint-check
on: ['push']
jobs:
  lint:
    runs-on: ['ubuntu-22.04']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.16'
      - run: pip install -r requirements.txt
      - run: pip install .
      - run: npm install
      - run: touch jnitrace/build/__init__.py
      - run: pylint jnitrace/jnitrace.py
      - run: npm run lint